### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [MCloud2/prj-rev-bwfs-dasmoto#2]
Overall met expectations

In this first project I look at two primary items with the main goal being to stop inefficient or bad practices early.

First is did you use divs, ids/classes to manage and organize your html content.

Great on this. 

Second is your css efficient and non repetitive.

Great on this also. You avoided the common mistakes I see on this first project.  My only issue is the unneeded use of font weight bold.

To prepare you for the upcoming projects I like you to go to flexboxfroggy.com. See how far you can get, the later projects uses flexbox heavily and this will help you immensely.

**Comment by MCloud2** [comment]
I appreciate the feedback, it has been a big help. Flexboxfroggy looks like it will be great practice for upcoming projects. Thanks for the recommendation!
